name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: latest

    - name: Install dependencies
      run: shards install

    - name: Check formatting
      run: crystal tool format --check

    - name: Run tests
      run: crystal spec

    - name: Build
      run: shards build